title: Center for Foundation Models and AI Agents for Science
navtitle: Center for Foundation Models and AI Agents for Science
url: scifm.ai

plugins:
- jekyll-seo-tag
- jekyll-sitemap

news:
  front_page_limit: 2

sass:
  sass_dir: /assets/css/_sass
  style: compressed

exclude:
  - .sass-cache

analytics:
  gtag: G-DGCRY7J6T8

roles:
  - key: pi
    name: Principal Investigators
  - key: director
    name: Director
  - key: assoc_director
    name: Associate Directors
  - key: faculty
    name: Faculty
  - key: team
    name: Students  
  - key: postdoc
    name: Postdoctoral Scholars
  - key: colab
    name: Collaborators

summer_school_roles:
  - key: organizer
    name: Core Organizers
  - key: hack
    name: Hackathon Organizers

collections:
  projects:
    output: true
  publications:
    output: true
    permalink: /:collection/:path/
