title: Center for Scientific Foundation Models
navtitle: Center for Scientific Foundation Models
url: abhutani2000.github.io  
baseurl: /scifm.github.io    com

plugins:
- jekyll-seo-tag
- jekyll-sitemap

news:
  front_page_limit: 5

sass:
  sass_dir: /assets/css/_sass
  style: compressed

exclude:
  - .sass-cache

analytics:
  gtag: G-DGCRY7J6T8

roles:
  - key: pi
    name: Principal Investigators
  - key: team
    name: Core Team
  - key: colab
    name: Collaborators

organizations:
  - key: um
    name: University of Michigan
  - key: anl
    name: Argonne National Laboratory

# make pages for the _projects folder
collections:
  projects:
    output: true
